In [1]:
from cinofinance.dividend import Dividend

In [2]:
Dividend().get_portfolio()

,Sep 22,Okt 22,Nov 22,Dez 22,Jan 23,Feb 23,Mrz 23,Apr 23,Mai 23,Jun 23,Jul 23,Aug 23,Sep 23,Okt 23,Nov 23,Dez 23,Jan 24,Feb 24
Tickers,,,,,,,,,,,,,,,,,,
AGNC,25,29,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
BNTX,1,1,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
MCO,1,1,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
MSFT,1,1,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
NVDA,2,2,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
ORC,7,15,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
STAG,11,11,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
V,1,1,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None

Tickers
AGNC    29
BNTX     1
MCO      1
MSFT     1
NVDA     2
ORC     15
STAG    11
V        1
Name: Okt 22, dtype: int64

In [5]:
portfolio = Dividend().get_portfolio()['Okt 22']

In [6]:
df = Dividend().get_portfolio_dividends(portfolio)
df

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

KeyError: 'Lot'